config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'static_pages#contact'
  match '/send_mail', to: 'static_pages#send_mail', via: 'post'
  devise_for :users
  resources :authors

  resources :articles, :except => [:index]

  resources :categories
  post 'search_country' => 'articles#search_country'
  get 'search_country' => 'articles#search_country' 
  root 'articles#index'
  get 'articles' => redirect('/')
  get 'about' => 'static_pages#about'
  get '/sitemap1.xml.gz' => 'sitemaps#show'
  # Example of regular route:
  devise_scope :user do
    get 'administration' => 'devise/sessions#new'
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_url :title
  def to_param
    url
  end  
  belongs_to :category
  belongs_to :country, :class_name => Country  
  belongs_to :author   
  validates_presence_of :title, :text1, :photo1,  :p1desescription, :category_id, :author_id
  has_attached_file :photo6, :styles => { :medium => "800x600>", :thumb => "300x300>" }
  validates_attachment_content_type :photo6, :content_type => /\Aimage\/.*\Z/ 
  has_attached_file :photo5, :styles => { :medium => "800x600>", :thumb => "300x300>" }
  validates_attachment_content_type :photo5, :content_type => /\Aimage\/.*\Z/ 
  has_attached_file :photo4, :styles => { :medium => "800x600>", :thumb => "300x300>" }
  validates_attachment_content_type :photo4, :content_type => /\Aimage\/.*\Z/ 
  has_attached_file :photo3, :styles => { :medium => "800x600>", :thumb => "300x300>" }
  validates_attachment_content_type :photo3, :content_type => /\Aimage\/.*\Z/ 
  has_attached_file :photo2, :styles => { :medium => "800x600>", :thumb => "300x300>" }
  validates_attachment_content_type :photo2, :content_type => /\Aimage\/.*\Z/ 
  has_attached_file :photo1, :styles => { :medium => "800x600>", :thumb => "300x300>" }
  validates_attachment_content_type :photo1, :content_type => /\Aimage\/.*\Z/ 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ApplicationHelper
  before_action :set_article, only: [:show, :edit, :update, :destroy]  
  before_action :check_isadmin?, only: [:new, :edit, :update, :create, :destroy] 

  def search_country
    if params.has_key?(:country_id)
      if params[:country_id].empty?
          @articles = Article.all.paginate(page: params[:page], per_page: 6).order('created_at DESC')
          @note = ""        
      else
        @articles = Article.where(country_id: params[:country_id]).paginate(page: params[:page], per_page: 6).order('created_at DESC')
        @country = Country.find(params[:country_id])
        @note = "Articles about #{@country.name}"
        if @articles.empty?
          @articles = Article.all.paginate(page: params[:page], per_page: 6).order('created_at DESC')
          @note = "There are no articles about #{@country.name}, yet. Consider writing one."
        end        
      end
      render action: 'index'
    end
  end  
  def index
    if request.get?
      if params.has_key?(:category_id)
        @articles =Article.where(category_id: params[:category_id]).paginate(page: params[:page], per_page: 6).order('created_at DESC')
        @category = Category.find(params[:category_id])
        @note = ""
        if @articles.empty?
          @artcles = Article.all.paginate(page: params[:page], per_page: 6).order('created_at DESC')
          @note = "There are no articles for this category, yet. Consider writing one."
        end        
      else
        @articles =Article.all.paginate(page: params[:page], per_page: 6).order('created_at DESC')
        @note = ""
      end
    end
    @slider_articles=Article.where(slider: true).order(:updated_at).reverse_order.limit(4)
    @did_articles=Article.where(category_id: 3).order(:updated_at).reverse_order.limit(10)
  end

  def show
    @authors_articles=Article.where(author_id: @article.author_id).order(:created_at).reverse_order.limit(6)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to(@article, notice: 'Article was successfully updated.')
    else
      render :edit
    end
  end
  def destroy
    @article.destroy
    redirect_to root_url, notice: 'Article was successfully destroyed.'
  end

  private
  
    def set_article
      @article = Article.find_by_url(params[:id])
    end  
  
    def article_params
      params.require(:article).permit(:title, :description, :text1, :text2, :text3, :text4, :text5, :text6, :p1desescription, :p2description, :p3description, :p4description, :p5description, :p6description, :title, :photo1, :photo2, :photo3, :photo4, :photo5, :photo6, :country_id, :category_id, :author_id, :slider)
    end   
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def description(content)
    sanitize(content.gsub(/<code[^<]*<\/code>/, ""), :tags => %w(), :attributes => %w()).gsub(/[\r\n?]/, " ").squeeze(" ").gsub(/\"/, "'")[0..250].strip
  end  
end

app/views/articles/_diduknow.html.erb
  <li class="list-group-item scrl-header" id="header-of-table-home">
    <h3 class="text-primary">Did You Know?</h3>
  </li>
<div id="demo" class="scroll-text scroll-container">    
<ul class="list-group lgdid">
<% @did_articles.each do |article| %>
  <li class="list-group-item" id="lidid">
  <%= link_to "articles/#{article.url}" do %>	
  <%= article.title %>
  <%end%>
  </li>
<% end %>
</ul>
</div>
<script>
  var sliderhgh = $('.sld').height();
  var headhgh = $('#header-of-table-home').height();
  var scrollrhgh = (sliderhgh - headhgh)/100 * 80
  scrollrhgh = Math.round(scrollrhgh);
  $('.scroll-container').css({'height':scrollrhgh+'px'});
</script>

app/views/articles/_form.html.haml
= form_for @article, :html => { :class => 'form-horizontal' } do |f|
  - if @article.errors.any?
    .row
      .col-lg-2
      .col-lg-8 
        .alert.alert-dismissable.alert-danger
          %strong= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
          %ul
            - @article.errors.full_messages.each do |msg|
              %li= msg       
      .col-lg-1       

  .form-group
    = f.label :title, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :title, class: 'form-control'
  .form-group
    .col-lg-12
      .checkbox
        %label
          = f.check_box :slider, class: 'form-control'
          ="Slider"      
  .form-group
    = f.label 'Category', :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.select :category_id, Category.all.map{|u| [ u.name, u.id ] } , {}, :class => 'form-control'       
  .form-group
    = f.label 'Country/territory', :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.select :country_id, Country.all.map{|u| [ u.name, u.id ] } , {}, :class => 'form-control'       
  .form-group
    = f.label 'Author', :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.select :author_id, Author.all.map{|u| [ u.fullname, u.id ] } , {}, :class => 'form-control'       

  .form-group
    = f.label :description, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :description, class: 'form-control'    
  .form-group
    = f.label :text1, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :text1, class: 'form-control'
  .form-group
    = f.label :photo1, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.file_field :photo1, class: 'form-control'
  .form-group
    = f.label "Photo 1 description", :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :p1desescription, class: 'form-control'    

  .form-group
    = f.label :text2, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :text2, class: 'form-control'
  .form-group
    = f.label :photo2, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.file_field :photo2, class: 'form-control'
  .form-group
    = f.label "Photo 2 description", :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :p2description, class: 'form-control'      

  .form-group
    = f.label :text3, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :text3, class: 'form-control'
  .form-group
    = f.label :photo3, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.file_field :photo3, class: 'form-control'
  .form-group
    = f.label "Photo 3 description", :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :p3description, class: 'form-control'         
    
  .form-group
    = f.label :text4, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :text4, class: 'form-control'
  .form-group
    = f.label :photo4, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.file_field :photo4, class: 'form-control'
  .form-group
    = f.label "Photo 4 description", :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :p4description, class: 'form-control'

  .form-group
    = f.label :text5, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :text5, class: 'form-control'
  .form-group
    = f.label :photo5, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.file_field :photo5, class: 'form-control'
  .form-group
    = f.label "Photo 5 description", :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :p5description, class: 'form-control'

  .form-group
    = f.label :text6, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :text6, class: 'form-control'
  .form-group
    = f.label :photo6, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.file_field :photo6, class: 'form-control'
  .form-group
    = f.label "Photo 6 description", :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :p6description, class: 'form-control'
      
  .form-group
    .col-lg-10.col-lg-offset-2
      =f.submit "Save article", :class => 'btn btn-primary'    

app/views/articles/_search_form.haml
=form_tag(search_country_path, :multipart => true, method: :post, :class => 'form-horizontal') do
  %h5.text-danger= 'COUNTRIES'
  .form-group
    .col-lg-12
      -@countries_s = Country.order('name ASC')
      = select_tag :country_id,  options_for_select(@countries_s.map{|u| [ u.name, u.id ] }), prompt: "Select a Country", :class => 'form-control'
  .form-group
    .col-lg-12
      = submit_tag "SEARCH", :class => 'btn btn-sm btn-primary'

app/views/articles/_slider.html.erb
<div class="row">
<div class="col-lg-12 col-md-12">
<div id="carousel-example-generic" class="carousel slide sldhold" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner sld">
  	<% @slider_articles.each_with_index do |article, index| %>
  	<% if index == 0 %>
    <div class="item active">
    <% else %>
    <div class="item">
    <% end %>
     <%= image_tag article.photo1(:medium), :height => "200px", :width => "100%", :alt => article.p1desescription %>
    <%= link_to "articles/#{article.url}" do%>
      <div class="carousel-caption">
      	<center>
        <div class="pozadina-slajder">
        	<h4 class="text-danger"><%= article.title%></h4>
        	<p class="text-danger"><small><%= article.description%></small></p>
        </div>
        </center>	
      </div>
	<%end%>	    
    </div>      
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
</div>
</div>
<script>
	var cw = $('.sld').width();
	var ch =  cw/100 * 55
	ch = Math.round(ch);
    $('.sld').css({'height':ch+'px'});
</script>

app/views/articles/edit.html.haml
.row
  .col-lg-3
  .col-lg-6
    %h1 Edit Article
    
    = render 'form'
    %center
      %br
        = link_to 'Back', root_path, :class => "btn btn-danger"
  .col-lg-3  

app/views/articles/ga_rights_show.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- article show sidebar -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-1030960367845799"
     data-ad-slot="3190756464"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/articles/index.html.haml
:javascript
  window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
  $(function () {
  $('#demo').scrollbox({
  linear: true,
  step: 1,
  delay: 0,
  speed: 40
  });
  });
-provide(:title, 'outstanding understanding')
-provide(:og_title, 'The Cultural Spotter - outstanding understanding')
-provide(:og_image, "https://s3.amazonaws.com/gtku/assets/about.png")
-content_for :description do
  = description('The Cultural Spotter is an online magazine that aims to show how colorful the world is by describing different lifestyles, culinary and cultural traditions and different points of view through a wide range of articles.')
.row.home-pd
  .col-lg-9.col-md-9
    %img{ :src => "https://s3.amazonaws.com/gtku/assets/frontpage.png", :width => "100%", :alt => "The Cultural Spotter Banner", :class => 'img-responsive' }
    - if request.env['ORIGINAL_FULLPATH'] == "/"
      .row
        .col-lg-8.col-md-7
          = render 'slider'
        .col-lg-4.col-md-5
          = render 'diduknow'
    %h2=@note
    -idx = 0
    -@articles.each_slice(6) do |articles_by6|
      .row    
        -articles_by6.each_slice(2) do |articles_by2|  
          .col-md-4.col-xs-12
            -articles_by2.each do |article|
              -idx = idx + 1
              -if(idx % 6 == 0) 
                -idx = 1 
              -if(idx % 5 == 0)
                -pnl = 'panel-primary'                           
              -elsif(idx % 4 == 0)
                -pnl = 'panel-info'                              
              -elsif(idx % 3 == 0)
                -pnl = 'panel-success'                                 
              -elsif(idx % 2 == 0)
                -pnl = 'panel-warning'              
              -elsif (idx % 1 == 0)
                -pnl = 'panel-danger'            
              .tar          
                = link_to "articles/#{article.url}" do
                  .panel{:class => pnl}     
                    .panel-heading 
                      %h3.panel-title.no-underline      
                        =article.title
                    .panel-body.trPic
                      = image_tag article.photo1(:medium),:width => "100%", :alt => article.p1desescription, :class => 'img-responsive'
                      .redO
                        %center=article.description
                .row
                  .col-md-4.col-xs-4
                    =article.created_at.to_date.to_s(:medium)
                  .col-md-4.col-xs-4
                    %p.text-danger=article.country.name             
                  .col-md-4.col-xs-4
                    .rgh
                      =article.category.name 
    .row
      .col-lg-12
        %center= will_paginate @articles                                     
  .col-lg-3.col-md-3
    .search-holder
      = render 'search_form'
    .fb-page{:data => {:href=>"https://www.facebook.com/theculturalspotter", "hide-cover"=>"false", "show-facepile"=>"true", "show-posts"=>"false"}}   
    .twt
      %a.twitter-follow-button{"data-lang" => "en","data-size" => "large", "data-show-count" => "true", :href => "https://twitter.com/CulturalSpotter"}
-# = render 'shared/fbpopup'     

app/views/articles/new.html.haml
.row
  .col-lg-3
  .col-lg-6
    %h1 New Article
    
    = render 'form'
    %center
      %br
        = link_to 'Back', root_path, :class => "btn btn-danger"
  .col-lg-3  

app/views/articles/show.html.haml
:javascript
  window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
-provide(:url, request.original_url)
-provide(:og_type, "article")
-provide(:og_title, @article.title)
-provide(:og_image, URI.join(request.url, @article.photo1.url))
-provide(:title, @article.title)
-content_for :description do
  = description(@article.description)
.row
  .col-lg-12
    %img{ :src => "https://s3.amazonaws.com/gtku/assets/frontpage.png", :width => "100%", :alt => "The Cultural Spotter Banner", :class => 'img-responsive' } 
.row
  .col-lg-1.col-md-1
  .col-lg-7.col-md-7
    %h2.text-danger=@article.title
    .row
      .col-lg-4.col-md-4
        %span=@article.created_at.to_date.to_s(:long)
      .col-lg-4.col-md-4
        %span.text-danger
          %b
            = succeed @article.country.name do
              %b.text-normal="Country/Region:&nbsp;&nbsp;".html_safe           
      .col-lg-4.col-md-4
        .rgh
          %span.text-warning
            %b
              = succeed @article.category.name do
                %b.text-normal="Category:&nbsp;&nbsp;".html_safe 
    %br              
    .blc
      =simple_format(@article.text1)
    -unless @article.photo1.blank?
      .row
        .col-lg-10
          .imageHolder
            = image_tag @article.photo1(:medium),:width => "100%", :alt => @article.p1desescription, :class => 'img-responsive'
              -unless @article.p1desescription.blank?
              .imageHolder.caption
                %white=@article.p1desescription
          .line-br        
        .col-lg-2       
    .blc
      =simple_format(@article.text2)
    -unless @article.photo2.blank?
      .row
        .col-lg-10
          .imageHolder
            = image_tag @article.photo2(:medium),:width => "100%", :alt => @article.p2description, :class => 'img-responsive'
              -unless @article.p2description.blank?
              .imageHolder.caption
                %white=@article.p2description
          .line-br
        .col-lg-2  
    .blc
      =simple_format(@article.text3)
    -unless @article.photo3.blank?
      .row
        .col-lg-10
          .imageHolder
            = image_tag @article.photo3(:medium),:width => "100%", :alt => @article.p3description, :class => 'img-responsive'
              -unless @article.p3description.blank?
              .imageHolder.caption
                %white=@article.p3description
          .line-br
        .col-lg-2               
    .blc
      =simple_format(@article.text4)
    -unless @article.photo4.blank?
      .row
        .col-lg-10
          .imageHolder
            = image_tag @article.photo4(:medium),:width => "100%", :alt => @article.p4description, :class => 'img-responsive'
              -unless @article.p4description.blank?
              .imageHolder.caption
                %white=@article.p4description
          .line-br
        .col-lg-2  
    .blc
      =simple_format(@article.text5)
    -unless @article.photo5.blank?
      .row
        .col-lg-10
          .imageHolder
            = image_tag @article.photo5(:medium),:width => "100%", :alt => @article.p5description, :class => 'img-responsive'
              -unless @article.p5description.blank?
              .imageHolder.caption
                %white=@article.p5description
          .line-br
        .col-lg-2  
    .blc
      =simple_format(@article.text6)
    -unless @article.photo6.blank?
      .row
        .col-lg-10
          .imageHolder
            = image_tag @article.photo6(:medium),:width => "100%", :alt => @article.p6description, :class => 'img-responsive'
              -unless @article.p6description.blank?
              .imageHolder.caption
                %white=@article.p6description
          .line-br
        .col-lg-2                                          
    %br    
      =render_shareable :buttons=> [ 'facebook','twitter', 'google_plus']
    -if current_user.try(:admin?)
      .alert
        =link_to 'Edit Article', edit_article_path(@article), :class => 'btn btn-primary'
        =link_to 'Back to Articles', root_path, :class => 'btn btn-danger'
        =link_to t('.destroy', :default => t("helpers.links.destroy")),
                article_path(@article),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger'
    .fb-comments{:data => {:href=>"https://www.theculturalspotter.com/articles/#{@article.url}", :numposts=>"5", :colorscheme=>"light"}}        
  .col-lg-4.col-md-4
    .jumbotron.jumb
      .row
        .col-md-3.col-xs-3
        .col-md-9.col-xs-9          
          %p.text-danger='About the Author'
      .row
        .col-lg-12
        .col-lg-12
          = image_tag @article.author.photo(:thumb), size: "150x150", :alt => "#{@article.author.first_name} #{@article.author.last_name}", :class => 'img-circle'
        .col-lg-12
        -if @article.author.link_profile.blank?  
          %h4=@article.author.fullname
          .jus
            %h3
              %small.authorabout
                =@article.author.about         
        -else
          %h4
            =link_to @article.author.fullname , @article.author.link_profile, :target => "_blank" 
          .jus
            %h3
              %small.authorabout
                =@article.author.about                      
    .fb-page{:data => {:href=>"https://www.facebook.com/theculturalspotter", "hide-cover"=>"false", "show-facepile"=>"true", "show-posts"=>"false"}}  
    .twt
      %a.twitter-follow-button{"data-lang" => "en","data-size" => "large", "data-show-count" => "true", :href => "https://twitter.com/CulturalSpotter"}
    -unless  @authors_articles.count == 1
      .list-group
        .list-group-item.lgi-heding
          %b='ARTICLES BY THE SAME AUTHOR'
        -@authors_articles.each do |authors_article|
          -unless authors_article.id == @article.id
            =link_to authors_article.title , article_path(authors_article), :class => "list-group-item" 
= render 'shared/fbpopup'            