config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'static_pages#contact'
  match '/send_mail', to: 'static_pages#send_mail', via: 'post'
  devise_for :users
  resources :authors

  resources :articles, :except => [:index]

  resources :categories
  post 'search_country' => 'articles#search_country'
  get 'search_country' => 'articles#search_country' 
  root 'articles#index'
  get 'articles' => redirect('/')
  get 'about' => 'static_pages#about'
  get '/sitemap1.xml.gz' => 'sitemaps#show'
  # Example of regular route:
  devise_scope :user do
    get 'administration' => 'devise/sessions#new'
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
  validates_presence_of :first_name, :last_name, :about, :photo
  has_attached_file :photo, :styles => { :thumb => "200x200>" }
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  
  def fullname
    self.first_name << " " << self.last_name
  end          
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  include ApplicationHelper
  before_action :check_isadmin?
  expose(:author, attributes: :author_params)
  expose(:authors)  

  def create
    self.author = Author.new(author_params)

    if author.save
      redirect_to author, notice: 'Author was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if author.update(author_params)
      redirect_to(author, notice: 'Author was successfully updated.')
    else
      render :edit
    end
  end
  def destroy
    author.destroy
    redirect_to authors_url, notice: 'Author was successfully destroyed.'
  end
  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :about, :link_profile, :photo)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.haml
= form_for author do |f|
  - if author.errors.any?
    #error_explanation
      %h2= "#{pluralize(author.errors.count, "error")} prohibited this author from being saved:"
      %ul
        - author.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control'
  .field
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control'
  .field
    = f.label :about
    = f.text_area :about, class: 'form-control'
  .field
    = f.label :photo  
    = f.file_field :photo, class: 'form-control'
  .field
    = f.label :link_profile
    = f.text_area :link_profile, class: 'form-control'
  = f.submit 'Save', :class => "btn btn-info"
%br

app/views/authors/edit.html.haml
.row
  .col-lg-3
  .col-lg-6
    %h1 Editing author
    
    = render 'form'
    
    = link_to 'Show', author, :class => "btn btn-primary"
    \|
    = link_to 'Back', authors_path, :class => "btn btn-danger"
  .col-lg-3
   

app/views/authors/index.html.haml
.row
  .col-lg-1
  .col-lg-10
    %h1 Authors
    
    %table.table.table-striped.table-bordered
      %tr
        %th First name
        %th Last name
        %th About
        %th Link profile
    
      - authors.each do |author|
        %tr
          %td= author.first_name
          %td= author.last_name
          %td= author.about              
          %td
            = link_to 'Show', author, :class => "btn btn-info"
            = link_to 'Edit', edit_author_path(author), :class => "btn btn-warning"
            = link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger"
    
    %br
    
    = link_to 'New author', new_author_path, :class => "btn btn-primary"
  .col-lg-1

app/views/authors/new.html.haml
.row
  .col-lg-3
  .col-lg-6
    %h1 New author
    
    = render 'form'
    
    = link_to 'Back', authors_path, :class => "btn btn-danger"
  .col-lg-3  

app/views/authors/show.html.haml
.row
  .col-lg-1
  .col-lg-5
    .jumbotron
      .row
        .col-md-3.col-xs-3
        .col-md-9.col-xs-9
          %p.text-danger='About Author'
      .row
        .col-md-1.col-xs-1
        .col-md-2.col-xs-3
          = image_tag author.photo(:thumb), size: "150x150", :class => 'img-circle img-responsive'
        .col-md-9.col-xs-8
        -if author.link_profile.blank?
          %h4=author.fullname
          .jus
            %strong=simple_format(author.about)          
        -else
          %h4
            =link_to author.fullname , author.link_profile, :target => "_blank"
          .jus
            %strong=author.about 
      
    .alert
      =link_to 'Edit Author', edit_author_path(author), :class => 'btn btn-primary'
      =link_to 'Back to Authors', authors_path, :class => 'btn btn-danger'
      =link_to t('.destroy', :default => t("helpers.links.destroy")),
              author_path(author),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger'      
  .col-lg-6