config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'static_pages#contact'
  match '/send_mail', to: 'static_pages#send_mail', via: 'post'
  devise_for :users
  resources :authors

  resources :articles, :except => [:index]

  resources :categories
  post 'search_country' => 'articles#search_country'
  get 'search_country' => 'articles#search_country' 
  root 'articles#index'
  get 'articles' => redirect('/')
  get 'about' => 'static_pages#about'
  get '/sitemap1.xml.gz' => 'sitemaps#show'
  # Example of regular route:
  devise_scope :user do
    get 'administration' => 'devise/sessions#new'
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.haml
%footer
	%br
	.row
		.col-lg-4
		.col-lg-4
			%center	
				%ul.breadcrumb
					%li.active
						%p.lead
							2015 © - THE CULTURAL SPOTTER
		.col-lg-4

app/views/layouts/_navbar.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand
        %img{ :src => "https://s3.amazonaws.com/gtku/assets/gtku-logo-basic.png", :height => "56", :width => "126", :alt => "The Cultural Spotter Logo" } 
      %button.navbar-toggle(type="button" data-toggle="collapse" data-target="#navbar-main")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse.collapse{:id => 'navbar-main'}
      %ul.nav.navbar-nav
        %li{ :class => is_active_page_home? }
          = link_to "Home", root_path, class: 'bold-text-navbar'
        %li{ :class => is_active_page?(about_path) }
          = link_to "About Us", about_path, class: 'bold-text-navbar'
        -categories = Category.all
        -categories.each do |category|
          %li{ :class => active_page_category(category.id) }
            = link_to category.name, root_path(:category_id => category.id), class: 'bold-text-navbar'
      %ul.nav.navbar-nav.navbar-right
        -if current_user.try(:admin?)
          %li= link_to "New Article", new_article_path, class: 'bold-text-navbar'
          %li= link_to "Categories", categories_path, class: 'bold-text-navbar'   
          %li= link_to "Authors", authors_path, class: 'bold-text-navbar'
          %li= link_to "Logout", destroy_user_session_path, :method => :delete, class: 'bold-text-navbar'    
        -else
          %li{ :class => is_active_page?(contact_path) }
            = link_to "Contact", contact_path, class: 'bold-text-navbar'

app/views/layouts/application.html.haml
%html(lang="en")
  %head
    %link{:href => "https://s3.amazonaws.com/gtku/assets/favicon.png", :rel => "icon", :type => "image/png"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title=full_title(yield(:title))
    %meta{:content => content_for?(:description) ? yield(:description) : "The Cultural Spotter - outstanding understanding", :name => "description"}/
    %meta{:name=> "viewport", :content=> "width=device-width, initial-scale=1, maximum-scale=1"}/
    %meta{:content => "773358454", :property => "fb:admins"}/
    %meta{:content => "1352131453", :property => "fb:admins"}/
    %meta{:content => content_for?(:og_type) ? yield(:og_type) : "website", :property => "og:type"}/
    %meta{:content => content_for?(:og_sitename) ? yield(:og_sitename) : "The Cultural Spotter", :property => "og:site_name"}/
    %meta{:content => content_for?(:og_title) ? yield(:og_title) : "TheCulturalSpotter-outstanding-understanding", :property => "og:title"}/
    %meta{:content => content_for?(:url) ? yield(:url) : "http://www.theculturalspotter.com", :property => "og:url"}/
    %meta{:content => content_for?(:description) ? yield(:description) : "The Cultural Spotter - outstanding understanding", :property => "og:description"}/
    %meta{:content => content_for?(:og_image) ? yield(:og_image) : "https://s3.amazonaws.com/gtku/assets/about.png", :property => "og:image"}/
    = stylesheet_link_tag    'journal', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'journal', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %noscript    
      %iframe{:height => "0", :width => "0", :style => "display:none;visibility:hidden", :src => "//www.googletagmanager.com/ns.html?id=GTM-NWXW76"}
    %script
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-NWXW76');    
    #fb-root
    %script
      (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));    
      
    = render 'layouts/navbar'
    -if alert       
      .row
        .col-lg-12
          .alert alert-dismissable.alert-danger
          %center
            %h4=alert
       
    -elsif notice
      .row
        .col-lg-12
          .alert.alert-dismissable.alert-success
            %center
              %h4= notice
    = yield
    = render 'layouts/footer'